### ISSUE TITLE
(FLK-E741) Do not use variables named 'l', 'O', or 'I'

### ISSUE THREAD

**Issue by Cryptex-github** [Cryptex-github/the-anime-bot-bot#61]
## Description
Variables named `I`, `O`, and `l` can be very hard to read. This is because the letter `I` and the letter `l` are easily confused, and the letter `O` and the number `0` can be easily confused. Change the names of these variables to something more descriptive.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Cryptex-github/the-anime-bot-bot/issue/FLK-E741/occurrences/](https://deepsource.io/gh/Cryptex-github/the-anime-bot-bot/issue/FLK-E741/occurrences/)

**Comment by drapespy** [comment]
wanna meet up alvin

**Comment by drapespy** [comment]
rn

**Comment by drapespy** [comment]
im on my way

**Comment by drapespy** [comment]
hi

**Comment by drapespy** [comment]
ik ur on here

**Comment by drapespy** [comment]
oh alvinnnn

**Comment by drapespy** [comment]
im almost there
