### ISSUE TITLE
imposter is too sus

### ISSUE THREAD

**Issue by jay3332** [Cryptex-github/the-anime-bot-bot#89]
It is now for the realization and/or acknowledgement that the particular stage in something's development or in a course of events of the continued progress of existence and events that last an unknown or unstated length of time in the past, present, and future regarded as a entirety, marked by exactness and accuracy of expression or detail, for which the human being, especially a person as distinguished from an animal or (in science fiction) an alien, is being regarded as an individual who speaks and acts so as to make it appear that something is the case when in fact it is not to be someone else in order to deceive others, especially for fraudulent gain, is at least somewhat having or showing a cautious feeling that someone or something cannot be relied upon of someone or something.

**Comment by Cryptex-github** [comment]
amongus

**Comment by Drxckzyz** [comment]
Amungusssssssss

**Comment by jottew** [comment]
kinda sussy
